Implement standard traits for pointers and bump version to 0.2.0
kaist-cp/circ pull request #3
Opened 2024-09-27 17:03 UTC by powergee

* Resolves #1 
  * For all pointer types, implemented `Debug` and `Pointer`.
  * For dereferenceable types (i.e., `Rc` and `Snapshot`), implemented `PartialOrd`, `Ord`, `PartialEq`, `Eq`, and `Hash`.
  * Implemented `From` by referring to [the type relation graph](https://github.com/kaist-cp/circ?tab=readme-ov-file#type-relation). 
* Resolves #2 
  * Now `Rc::eq` and `Snapshot::eq` compare by objects they are pointing to. To compare by pointer values, use the `ptr_eq` method instead.
  * This patch is a breaking-change because it changes the behavior of a pre-existing API. Therefore, we need to increment the non-zero left-most version number (i.e., `0.1.0` -> `0.2.0`).

2024-09-28 05:44 UTC, tomtomjhj approved these changes

2024-09-30 07:00 UTC, jeehoonkang requested changes

2024-09-30 07:00 UTC, jeehoonkang commented on src/strong.rs
> +            (None, None) => true,
3, 1 case 먼저 얘기하고
나머지는 걍 _, _ 로 처리하면 어떨지?

2024-09-30 07:03 UTC, Lee-Janggun commented on src/ebr_impl/pointers.rs
> +        self.inner.ptr_eq(other.inner)
RawShared도 그냥 PartialEq 구현은 삭제하고 ptr_eq만 남기는게 맞지 않을까요?

2024-09-30 07:13 UTC, powergee commented on Cargo.toml
> +version = "0.2.0"
Rust에서는 incompatible한 change가 발생할 경우 가장 왼쪽의 non-zero version을 올릴 것을 권장하고 있습니다.
엄밀히 보면 `eq` 메서드의 behavior가 바뀐다는 점 때문에 major 버전을 올린 것인데, minor한 change이긴 합니다.
그냥 patch version을 올리는 것으로(i.e. `0.1.1`) 할까요?

2024-09-30 07:50 UTC, powergee commented on Cargo.toml
> +version = "0.2.0"
Prematurely resolved in [92d280989cb9d80fea1f49163af3d0b8b45b095c](https://github.com/kaist-cp/circ/pull/3/commits/92d280989cb9d80fea1f49163af3d0b8b45b095c).

2024-09-30 07:55 UTC, powergee commented on src/ebr_impl/pointers.rs
> +        self.inner.ptr_eq(other.inner)
* @jeehoonkang Resolved in [b5f869835f1fdd4a7380a26ca2feb38f942a4ac9](https://github.com/kaist-cp/circ/pull/3/commits/b5f869835f1fdd4a7380a26ca2feb38f942a4ac9).
* @Lee-Janggun Resolved in [97e7a22c0e6e396899a7935a339939cf85f4bc42](https://github.com/kaist-cp/circ/pull/3/commits/97e7a22c0e6e396899a7935a339939cf85f4bc42).

2024-09-30 07:55 UTC, powergee commented on src/strong.rs
> +            (None, None) => true,
Resolved in [7e99db905aec7f5ca0f452d225f8977fb9711b58](https://github.com/kaist-cp/circ/pull/3/commits/7e99db905aec7f5ca0f452d225f8977fb9711b58).

2024-09-30 07:58 UTC, Lee-Janggun commented on src/strong.rs
> +        match (self.as_ref(), other.as_ref()) {
지금 구현하신거 걍 `self.as_ref() == other.as_ref()` 아닌가요?

2024-09-30 08:36 UTC, powergee commented on src/strong.rs
> +        match (self.as_ref(), other.as_ref()) {
앗 [`Option::<&T>::eq`](https://doc.rust-lang.org/src/core/option.rs.html#2190-2202)가 이미 그렇게 구현되어있었네요... 감사합니다, 수정했습니다: [c243aa25b4f12600c70c0458732e9c346a523358](https://github.com/kaist-cp/circ/pull/3/commits/c243aa25b4f12600c70c0458732e9c346a523358)

2024-09-30 09:18 UTC, jeehoonkang commented on Cargo.toml
> +version = "0.2.0"
전 bug fix라고 느껴져서 0.1.1 도 좋습니다만, 0.2.0도 나쁘지 않은 것 같긴 합니다... 정현님이 결정해주세요.

release note에 ptr_eq 변경 애기를 쓰긴 해야할듯 합니다. 적절한 release note 형식을 이 PR에서 도입하는 것도 좋겠습니다.

2024-10-03 08:40 UTC, powergee commented on Cargo.toml
> +version = "0.2.0"
Rust `clap` 프로젝트를 참고해서, 리포에 `CHANGELOG.md`라는 파일을 만드려고 합니다. 이제 새로운 release를 할 때마다 아래와 같은 방법으로 로그를 관리하는 방안을 생각하고 있습니다.

1. 이 파일에 수정 내역과 (breaking change일 경우) migration 방법 등을 설명
2. [GitHub Releases](https://github.com/kaist-cp/circ/releases)에 커밋을 등록

위 지침은 `CHANGELOG.md`에도 적어두겠습니다.

2024-10-03 08:56 UTC, powergee commented on Cargo.toml
> +version = "0.2.0"
> 전 bug fix라고 느껴져서 0.1.1 도 좋습니다만, 0.2.0도 나쁘지 않은 것 같긴 합니다... 정현님이 결정해주세요.

넵, 알겠습니다. 저는 0.2.0으로 릴리스하는 것이 더 적절하다고 생각합니다. 이전 behavior가 버그였다기보단 널리 쓰이던 컨벤션을 따르지 않고 있었던 것이고, 이번에 그것을 따르게 되면서 이전 behavior를 따르던 코드가 틀리게 될 가능성이 있기 때문입니다 (예를 들어 우리의 [HList 예시 코드](https://github.com/kaist-cp/circ/blob/main/tests/harris_list.rs)도 수정이 필요했습니다).

2024-10-03 09:05 UTC, powergee commented on Cargo.toml
> +version = "0.2.0"
위 사항을 반영(0.2.0으로 bump & Change log 작성)해서 force push했습니다. 이 PR이 머지되고 나면 GitHub & crates.io에 release를 등록하겠습니다.

2024-10-03 16:22 UTC, jeehoonkang requested changes

2024-10-03 16:22 UTC, jeehoonkang commented on CHANGELOG.md
> +* Added implementation of standard traits for pointers. ([#3](https://github.com/kaist-cp/circ/pull/3))
이거 아마 "#3" 이라고만 써도 깃헙이 알아서 렌더링잘 해주진 않는지..? 확인 한번 부탁...

2024-10-03 16:22 UTC, jeehoonkang commented on CHANGELOG.md
> +## Version 0.2.0 - 2024-10-03
제일 위에 "## Unreleased" 를 놓고, 매 수정마다 changelog에 쓸 얘기를 조금씩 넣어두면 좋을듯

2024-10-04 05:50 UTC, simnalamburt commented on Cargo.toml
> +version = "0.2.0"
어차피 기존에 사용자가 많지 않았어서 0.2.0 bump가 크게 문제가 없을것같습니다

2024-10-04 05:52 UTC, simnalamburt commented on CHANGELOG.md
> +* Added implementation of standard traits for pointers. ([#3](https://github.com/kaist-cp/circ/pull/3))
> 알아서 렌더링잘 해주진 않는지..?

그 동작은 커밋메시지, 깃헙이슈, PR, 댓글 에서만 일어나고 git에 체크인되어있는 마크다운에서는 발생하지 않아요.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/2e7d3bf6-633c-4084-98e8-43e3633a7b40">

2024-10-04 05:53 UTC, simnalamburt commented on CHANGELOG.md
> +## Version 0.2.0 - 2024-10-03
```suggestion
## Unreleased
<!-- TODO -->

## Version 0.2.0 - 2024-10-03
```

2024-10-04 08:32 UTC, powergee commented on CHANGELOG.md
> +* Added implementation of standard traits for pointers. ([#3](https://github.com/kaist-cp/circ/pull/3))
@simnalamburt 감사합니다!

2024-10-04 08:36 UTC, merged